---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: util
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: util
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: util
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: util
subjects:
  - kind: ServiceAccount
    name: util
    namespace: default
