apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp
  labels:
    app: kubernetes-bootcamp
  namespace: default
spec:
  type: NodePort
  selector:
    app: kubernetes-bootcamp
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  sessionAffinity: None
